name: Builds

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:

  windows:
    permissions: write-all
    runs-on: windows-latest

    steps:
      - name: Checking Latest Commit
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Run Cache
        uses: actions/cache@v3
        with:
          # not caching the bin folder to prevent asset duplication and stuff like that
          key: windows-build-cache
          path: |
            .haxelib/
            export/build/windows/haxe/
            export/build/windows/obj/
          restore-keys: windows-build-cache

      - name: Install Libraries
        run: haxe -cp commandline -D analyzer-optimize --run Main setup

      - name: Compile Engine
        run: haxelib run lime build windows -final

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: Windows
          path: export/build/windows/bin
          overwrite: true
          include-hidden-files: true
          if-no-files-found: error

      - name: Clearing Cache
        uses: actions/github-script@v6
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == 'windows-build-cache') {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log('Cache cleared.')
              }
            }

      - name: Run New Cache
        uses: actions/cache@v3
        with:
          # not caching the bin folder to prevent asset duplication and stuff like that
          key: windows-build-cache
          path: |
            .haxelib/
            export/build/windows/haxe/
            export/build/windows/obj/
          restore-keys: windows-build-cache